/** Auto-generated by pnpm compile; do not edit manually. */
export const DISPUTE_RESOLUTION_ABI = [
	{
		inputs: [
			{
				internalType: "address",
				name: "_jobEscrow",
				type: "address",
			},
		],
		stateMutability: "nonpayable",
		type: "constructor",
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "owner",
				type: "address",
			},
		],
		name: "OwnableInvalidOwner",
		type: "error",
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "account",
				type: "address",
			},
		],
		name: "OwnableUnauthorizedAccount",
		type: "error",
	},
	{
		inputs: [],
		name: "ReentrancyGuardReentrantCall",
		type: "error",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "uint256",
				name: "disputeId",
				type: "uint256",
			},
			{
				indexed: true,
				internalType: "uint256",
				name: "jobId",
				type: "uint256",
			},
			{
				indexed: true,
				internalType: "address",
				name: "creator",
				type: "address",
			},
		],
		name: "DisputeCreated",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "uint256",
				name: "disputeId",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "enum DisputeResolution.DisputeStatus",
				name: "finalStatus",
				type: "uint8",
			},
			{
				indexed: false,
				internalType: "string",
				name: "resolution",
				type: "string",
			},
		],
		name: "DisputeResolved",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "previousOwner",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "newOwner",
				type: "address",
			},
		],
		name: "OwnershipTransferred",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "uint256",
				name: "disputeId",
				type: "uint256",
			},
			{
				indexed: true,
				internalType: "address",
				name: "voter",
				type: "address",
			},
			{
				indexed: false,
				internalType: "enum DisputeResolution.VoteChoice",
				name: "choice",
				type: "uint8",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "weight",
				type: "uint256",
			},
		],
		name: "Voted",
		type: "event",
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "_jobId",
				type: "uint256",
			},
			{
				internalType: "string",
				name: "_evidenceHash",
				type: "string",
			},
		],
		name: "createDispute",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "",
				type: "uint256",
			},
		],
		name: "disputes",
		outputs: [
			{
				internalType: "uint256",
				name: "jobId",
				type: "uint256",
			},
			{
				internalType: "address",
				name: "creator",
				type: "address",
			},
			{
				internalType: "string",
				name: "evidenceHash",
				type: "string",
			},
			{
				internalType: "enum DisputeResolution.DisputeStatus",
				name: "status",
				type: "uint8",
			},
			{
				internalType: "uint256",
				name: "votingStartsAt",
				type: "uint256",
			},
			{
				internalType: "uint256",
				name: "votingEndsAt",
				type: "uint256",
			},
			{
				internalType: "uint256",
				name: "approveVotesCount",
				type: "uint256",
			},
			{
				internalType: "uint256",
				name: "rejectVotesCount",
				type: "uint256",
			},
			{
				internalType: "uint256",
				name: "totalWeight",
				type: "uint256",
			},
			{
				internalType: "bool",
				name: "resolved",
				type: "bool",
			},
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "jobEscrow",
		outputs: [
			{
				internalType: "contract IJobEscrow",
				name: "",
				type: "address",
			},
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "nextDisputeId",
		outputs: [
			{
				internalType: "uint256",
				name: "",
				type: "uint256",
			},
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "owner",
		outputs: [
			{
				internalType: "address",
				name: "",
				type: "address",
			},
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "renounceOwnership",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "_disputeId",
				type: "uint256",
			},
		],
		name: "resolveDispute",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "_period",
				type: "uint256",
			},
		],
		name: "setVotingPeriod",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{
				internalType: "address",
				name: "newOwner",
				type: "address",
			},
		],
		name: "transferOwnership",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "_disputeId",
				type: "uint256",
			},
			{
				internalType: "enum DisputeResolution.VoteChoice",
				name: "_choice",
				type: "uint8",
			},
		],
		name: "vote",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{
				internalType: "uint256",
				name: "",
				type: "uint256",
			},
			{
				internalType: "address",
				name: "",
				type: "address",
			},
		],
		name: "votes",
		outputs: [
			{
				internalType: "enum DisputeResolution.VoteChoice",
				name: "choice",
				type: "uint8",
			},
			{
				internalType: "uint256",
				name: "weight",
				type: "uint256",
			},
			{
				internalType: "bool",
				name: "exists",
				type: "bool",
			},
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "votingPeriod",
		outputs: [
			{
				internalType: "uint256",
				name: "",
				type: "uint256",
			},
		],
		stateMutability: "view",
		type: "function",
	},
] as const
