/** Auto-generated by pnpm compile; do not edit manually. */
export const I_WALLET_ABI = [
	{
		inputs: [
			{
				internalType: "address",
				name: "user",
				type: "address",
			},
		],
		name: "depositEarnings",
		outputs: [],
		stateMutability: "payable",
		type: "function",
	},
] as const
