const fs = require("node:fs");
const path = require("node:path");

const artifactsDir = path.join(__dirname, "..", "..", "artifacts", "contracts");
const outputDir = path.join(__dirname, "..", "..", "src", "abis");

/**
 * 将合约名转换为常量名
 * 例如: JobEscrow -> JOB_ESCROW_ABI
 */
function toConstantName(contractName) {
  return (
    contractName
      .replace(/([A-Z])/g, "_$1")
      .toUpperCase()
      .replace(/^_/, "") + "_ABI"
  );
}

/**
 * 递归扫描 artifacts/contracts 目录，找到所有合约
 * 只导出主合约文件，过滤掉 Interface 等辅助合约
 */
function findContracts(dir, contracts = []) {
  if (!fs.existsSync(dir)) {
    return contracts;
  }

  const files = fs.readdirSync(dir);

  for (const file of files) {
    const fullPath = path.join(dir, file);
    const stat = fs.statSync(fullPath);

    if (stat.isDirectory()) {
      // 从目录名推断主合约名（去掉 .sol 后缀）
      const expectedContractName = path.basename(file, ".sol");
      
      // 递归扫描子目录
      findContracts(fullPath, contracts);
      
      // 检查是否存在与目录名匹配的主合约 JSON 文件
      const mainContractPath = path.join(fullPath, `${expectedContractName}.json`);
      if (fs.existsSync(mainContractPath)) {
        contracts.push({
          name: expectedContractName,
          artifactPath: mainContractPath,
        });
      }
    }
  }

  return contracts;
}

/**
 * 导出单个合约的 ABI
 */
function exportABI(contract) {
  try {
    const artifact = JSON.parse(fs.readFileSync(contract.artifactPath, "utf8"));
    const abi = artifact.abi;

    if (!abi || abi.length === 0) {
      console.warn(`⚠️  Empty ABI: ${contract.name} (skipping)`);
      return false;
    }

    const outputPath = path.join(outputDir, `${contract.name}.ts`);
    const constantName = toConstantName(contract.name);

    fs.mkdirSync(outputDir, { recursive: true });

    const header = "/** Auto-generated by pnpm compile; do not edit manually. */\n";
    const body =
      header +
      `export const ${constantName} = ` +
      JSON.stringify(abi, null, 2) +
      " as const;\n";

    fs.writeFileSync(outputPath, body);
    console.log(`✅ ${contract.name} -> ${constantName}`);
    return true;
  } catch (error) {
    console.error(`❌ Failed to export ${contract.name}:`, error.message);
    return false;
  }
}

function main() {
  console.log("🔧 Scanning for contracts...\n");

  const contracts = findContracts(artifactsDir);

  if (contracts.length === 0) {
    console.warn("⚠️  No contracts found. Run 'pnpm hardhat compile' first.");
    process.exit(1);
  }

  console.log(`📦 Found ${contracts.length} contract(s)\n`);

  let successCount = 0;
  for (const contract of contracts) {
    if (exportABI(contract)) {
      successCount++;
    }
  }

  console.log(`\n✨ Exported ${successCount}/${contracts.length} ABIs to ${outputDir}`);
}

main();
